; PlatformIO Project Configuration File
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;set default_envs to whichever board(s) you use. Build/Run/etc processes those envs
default_envs =
  esp32dev

[env]
; Global data for all [env:***]
framework = arduino
lib_ldf_mode = deep
upload_speed = 2000000
monitor_speed = 115200
lib_deps =
  SignalK/SensESP@>=3.0.0-beta.6,<4.0.0-alpha.1
  SensESP/OneWire@^3.0.1

 	pfeerick/elapsedMillis
  adafruit/Adafruit SSD1306@^2.5.1
  adafruit/Adafruit SH110X @ ^2.1.10
  ttlappalainen/NMEA2000-library@^4.17.2
  ttlappalainen/NMEA2000_esp32@^1.0.3

  adafruit/Adafruit ADS1X15@^2.3.0
  maffooclock/ESP32RotaryEncoder @1.1.0

  olikraus/U8g2 @ ^2.35.7

[espressif32_base]
;this section has config items common to all ESP32 boards
platform = espressif32 @ 6.6.0
build_unflags =
  -Werror=reorder
board_build.partitions = min_spiffs.csv
monitor_filters = esp32_exception_decoder

[env:esp32dev]
extends = espressif32_base
board = esp32dev
build_type = release  ;set to release for production, or debug for inspection
build_flags =
  -D LED_BUILTIN=2
  -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
  -D TAG='"Arduino"'
  -D "APP_VERSION=\"Prod 14\""
  -D DEBUG_DISABLED     ; Uncomment the following to disable debug output altogether
  -D DEBUG_DISABLE_JW   ;uncomment to hide all jw added Serial.printf statements
  ;-D REMOTE_DEBUG      ;Uncomment to enable the remote debug telnet interface on port 23
  -I include


build_src_filter =
  -<main_debug_test-01.cpp>
  -<main_string_test.cpp>
  -<main-liveDisplay-dev-01.cpp>
  -<main-template.cpp>
  -<main-TempsAndTanks-dev-011.cpp>
  -<main-TempsAndTanks-dev-012.cpp>
  -<main-TempsAndTanks-prod-011.cpp>
  -<main-TempsAndTanks-dev-013.cpp>
  -<main-TempsAndTanks-dev-014.cpp>
  +<main-TempsAndTanks-prod-014.cpp>

